apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  namespace: smartorder
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: ghostluzer/order-service:latest
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: order
  namespace: smartorder
spec:
  selector:
    app: order
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082