server:
  port: 8082

spring:
  application:
    name: order

order:
  validation:
    url: http://localhost:8081/validateOrder


management:
  endpoints:
    web:
      exposure:
        include: "*"
